### ISSUE TITLE
Code testing

### ISSUE THREAD

**Issue by jcgrenier** [pedramvdl31/Smart-City-Response-to-Homelessness#1]
Hello @pedramvdl31 ,

I'm presently testing your code! I have an error when I'm trying to make it run by just doing a `python RunAll.py` command.
It throws me an error that the Module `newFuncs` is not found. Is there anything missing? 

*We found it* We need to rename the file funcs.py to newFuncs.py.

Thanks!

**Comment by pedramvdl31** [comment]
> Hello @pedramvdl31 ,
> 
> I'm presently testing your code! I have an error when I'm trying to make it run by just doing a `python RunAll.py` command. It throws me an error that the Module `newFuncs` is not found. Is there anything missing?
> 
> _We found it_ We need to rename the file funcs.py to newFuncs.py.
> 
> Thanks!
@jcgrenier 

I see. Let me take a look.

**Comment by pedramvdl31** [comment]
@jcgrenier I made a new commit. The bug is fixed. run python3 RunAll.py

**Comment by pedramvdl31** [comment]
@jcgrenier Don't forget to pull the new changes. 
https://github.com/pedramvdl31/Smart-City-Response-to-Homelessness/commit/59953f9e3c398af28fa46893e1cb9aaf992cdad0

**Comment by jcgrenier** [comment]
Thanks!

**Comment by pedramvdl31** [comment]
Thanks for bringing this bug to my attention!
